[workspace]
members = ["crates/un-i18n"]
resolver = "2"

[workspace.package]
edition = "2024"
authors = ["usagi / USAGI.NETWORK"]
license = "MIT"
repository = "https://github.com/usagi/un-common"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "0.8"
rust-i18n = "4"
regex = "1"
sys-locale = "0.3"
unic-langid = "0.9"
tracing = "0.1"
anyhow = "1"
thiserror = "2"
tauri = { version = "2", default-features = false }
